name: Backend Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Adjust to your Node.js version

      - name: Set working directory to the project directory
        run: cd client
        working-directory: $GITHUB_WORKSPACE

      - name: Install dependencies
        run: npm install # Replace with your package manager (e.g., yarn)
      - name: Run backend tests
        run: npm test # Replace with the actual test command
