name: Frontend Tests

on: [push]

jobs:
  component-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install
        working-directory: ./client

      - name: Run Component Tests
        run: npm run cypress:component
        working-directory: ./client
      - name: Track Workflow Duration
        run: echo "Workflow ran for $((GITHUB_RUN_DURATION / 60)) minutes."

  e2e-tests:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress.io
        uses: cypress-io/github-action@v6.6.0     
        with:
          working-directory: ./client
          build: npm run build
          start: npm start
      - name: Track Workflow Duration
        run: echo "Workflow ran for $((GITHUB_RUN_DURATION / 60)) minutes."
